package com.gk.model;

import java.util.ArrayList;
import java.util.List;

public class ThesisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public ThesisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andThesisCodeIsNull() {
            addCriterion("thesis_code is null");
            return (Criteria) this;
        }

        public Criteria andThesisCodeIsNotNull() {
            addCriterion("thesis_code is not null");
            return (Criteria) this;
        }

        public Criteria andThesisCodeEqualTo(String value) {
            addCriterion("thesis_code =", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeNotEqualTo(String value) {
            addCriterion("thesis_code <>", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeGreaterThan(String value) {
            addCriterion("thesis_code >", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_code >=", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeLessThan(String value) {
            addCriterion("thesis_code <", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeLessThanOrEqualTo(String value) {
            addCriterion("thesis_code <=", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeLike(String value) {
            addCriterion("thesis_code like", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeNotLike(String value) {
            addCriterion("thesis_code not like", value, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeIn(List<String> values) {
            addCriterion("thesis_code in", values, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeNotIn(List<String> values) {
            addCriterion("thesis_code not in", values, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeBetween(String value1, String value2) {
            addCriterion("thesis_code between", value1, value2, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisCodeNotBetween(String value1, String value2) {
            addCriterion("thesis_code not between", value1, value2, "thesisCode");
            return (Criteria) this;
        }

        public Criteria andThesisTitleIsNull() {
            addCriterion("thesis_title is null");
            return (Criteria) this;
        }

        public Criteria andThesisTitleIsNotNull() {
            addCriterion("thesis_title is not null");
            return (Criteria) this;
        }

        public Criteria andThesisTitleEqualTo(String value) {
            addCriterion("thesis_title =", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleNotEqualTo(String value) {
            addCriterion("thesis_title <>", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleGreaterThan(String value) {
            addCriterion("thesis_title >", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_title >=", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleLessThan(String value) {
            addCriterion("thesis_title <", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleLessThanOrEqualTo(String value) {
            addCriterion("thesis_title <=", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleLike(String value) {
            addCriterion("thesis_title like", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleNotLike(String value) {
            addCriterion("thesis_title not like", value, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleIn(List<String> values) {
            addCriterion("thesis_title in", values, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleNotIn(List<String> values) {
            addCriterion("thesis_title not in", values, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleBetween(String value1, String value2) {
            addCriterion("thesis_title between", value1, value2, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisTitleNotBetween(String value1, String value2) {
            addCriterion("thesis_title not between", value1, value2, "thesisTitle");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorIsNull() {
            addCriterion("thesis_author is null");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorIsNotNull() {
            addCriterion("thesis_author is not null");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorEqualTo(String value) {
            addCriterion("thesis_author =", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorNotEqualTo(String value) {
            addCriterion("thesis_author <>", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorGreaterThan(String value) {
            addCriterion("thesis_author >", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_author >=", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorLessThan(String value) {
            addCriterion("thesis_author <", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorLessThanOrEqualTo(String value) {
            addCriterion("thesis_author <=", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorLike(String value) {
            addCriterion("thesis_author like", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorNotLike(String value) {
            addCriterion("thesis_author not like", value, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorIn(List<String> values) {
            addCriterion("thesis_author in", values, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorNotIn(List<String> values) {
            addCriterion("thesis_author not in", values, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorBetween(String value1, String value2) {
            addCriterion("thesis_author between", value1, value2, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorNotBetween(String value1, String value2) {
            addCriterion("thesis_author not between", value1, value2, "thesisAuthor");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnIsNull() {
            addCriterion("thesis_isbn is null");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnIsNotNull() {
            addCriterion("thesis_isbn is not null");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnEqualTo(String value) {
            addCriterion("thesis_isbn =", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnNotEqualTo(String value) {
            addCriterion("thesis_isbn <>", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnGreaterThan(String value) {
            addCriterion("thesis_isbn >", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_isbn >=", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnLessThan(String value) {
            addCriterion("thesis_isbn <", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnLessThanOrEqualTo(String value) {
            addCriterion("thesis_isbn <=", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnLike(String value) {
            addCriterion("thesis_isbn like", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnNotLike(String value) {
            addCriterion("thesis_isbn not like", value, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnIn(List<String> values) {
            addCriterion("thesis_isbn in", values, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnNotIn(List<String> values) {
            addCriterion("thesis_isbn not in", values, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnBetween(String value1, String value2) {
            addCriterion("thesis_isbn between", value1, value2, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisIsbnNotBetween(String value1, String value2) {
            addCriterion("thesis_isbn not between", value1, value2, "thesisIsbn");
            return (Criteria) this;
        }

        public Criteria andThesisPagesIsNull() {
            addCriterion("thesis_pages is null");
            return (Criteria) this;
        }

        public Criteria andThesisPagesIsNotNull() {
            addCriterion("thesis_pages is not null");
            return (Criteria) this;
        }

        public Criteria andThesisPagesEqualTo(String value) {
            addCriterion("thesis_pages =", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesNotEqualTo(String value) {
            addCriterion("thesis_pages <>", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesGreaterThan(String value) {
            addCriterion("thesis_pages >", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_pages >=", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesLessThan(String value) {
            addCriterion("thesis_pages <", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesLessThanOrEqualTo(String value) {
            addCriterion("thesis_pages <=", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesLike(String value) {
            addCriterion("thesis_pages like", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesNotLike(String value) {
            addCriterion("thesis_pages not like", value, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesIn(List<String> values) {
            addCriterion("thesis_pages in", values, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesNotIn(List<String> values) {
            addCriterion("thesis_pages not in", values, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesBetween(String value1, String value2) {
            addCriterion("thesis_pages between", value1, value2, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisPagesNotBetween(String value1, String value2) {
            addCriterion("thesis_pages not between", value1, value2, "thesisPages");
            return (Criteria) this;
        }

        public Criteria andThesisSourceIsNull() {
            addCriterion("thesis_source is null");
            return (Criteria) this;
        }

        public Criteria andThesisSourceIsNotNull() {
            addCriterion("thesis_source is not null");
            return (Criteria) this;
        }

        public Criteria andThesisSourceEqualTo(String value) {
            addCriterion("thesis_source =", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceNotEqualTo(String value) {
            addCriterion("thesis_source <>", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceGreaterThan(String value) {
            addCriterion("thesis_source >", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_source >=", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceLessThan(String value) {
            addCriterion("thesis_source <", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceLessThanOrEqualTo(String value) {
            addCriterion("thesis_source <=", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceLike(String value) {
            addCriterion("thesis_source like", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceNotLike(String value) {
            addCriterion("thesis_source not like", value, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceIn(List<String> values) {
            addCriterion("thesis_source in", values, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceNotIn(List<String> values) {
            addCriterion("thesis_source not in", values, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceBetween(String value1, String value2) {
            addCriterion("thesis_source between", value1, value2, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisSourceNotBetween(String value1, String value2) {
            addCriterion("thesis_source not between", value1, value2, "thesisSource");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserIsNull() {
            addCriterion("thesis_adviser is null");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserIsNotNull() {
            addCriterion("thesis_adviser is not null");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserEqualTo(String value) {
            addCriterion("thesis_adviser =", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserNotEqualTo(String value) {
            addCriterion("thesis_adviser <>", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserGreaterThan(String value) {
            addCriterion("thesis_adviser >", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_adviser >=", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserLessThan(String value) {
            addCriterion("thesis_adviser <", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserLessThanOrEqualTo(String value) {
            addCriterion("thesis_adviser <=", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserLike(String value) {
            addCriterion("thesis_adviser like", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserNotLike(String value) {
            addCriterion("thesis_adviser not like", value, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserIn(List<String> values) {
            addCriterion("thesis_adviser in", values, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserNotIn(List<String> values) {
            addCriterion("thesis_adviser not in", values, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserBetween(String value1, String value2) {
            addCriterion("thesis_adviser between", value1, value2, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisAdviserNotBetween(String value1, String value2) {
            addCriterion("thesis_adviser not between", value1, value2, "thesisAdviser");
            return (Criteria) this;
        }

        public Criteria andThesisNotesIsNull() {
            addCriterion("thesis_notes is null");
            return (Criteria) this;
        }

        public Criteria andThesisNotesIsNotNull() {
            addCriterion("thesis_notes is not null");
            return (Criteria) this;
        }

        public Criteria andThesisNotesEqualTo(String value) {
            addCriterion("thesis_notes =", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesNotEqualTo(String value) {
            addCriterion("thesis_notes <>", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesGreaterThan(String value) {
            addCriterion("thesis_notes >", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_notes >=", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesLessThan(String value) {
            addCriterion("thesis_notes <", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesLessThanOrEqualTo(String value) {
            addCriterion("thesis_notes <=", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesLike(String value) {
            addCriterion("thesis_notes like", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesNotLike(String value) {
            addCriterion("thesis_notes not like", value, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesIn(List<String> values) {
            addCriterion("thesis_notes in", values, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesNotIn(List<String> values) {
            addCriterion("thesis_notes not in", values, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesBetween(String value1, String value2) {
            addCriterion("thesis_notes between", value1, value2, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisNotesNotBetween(String value1, String value2) {
            addCriterion("thesis_notes not between", value1, value2, "thesisNotes");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsIsNull() {
            addCriterion("thesis_keywords is null");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsIsNotNull() {
            addCriterion("thesis_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsEqualTo(String value) {
            addCriterion("thesis_keywords =", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsNotEqualTo(String value) {
            addCriterion("thesis_keywords <>", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsGreaterThan(String value) {
            addCriterion("thesis_keywords >", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_keywords >=", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsLessThan(String value) {
            addCriterion("thesis_keywords <", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsLessThanOrEqualTo(String value) {
            addCriterion("thesis_keywords <=", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsLike(String value) {
            addCriterion("thesis_keywords like", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsNotLike(String value) {
            addCriterion("thesis_keywords not like", value, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsIn(List<String> values) {
            addCriterion("thesis_keywords in", values, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsNotIn(List<String> values) {
            addCriterion("thesis_keywords not in", values, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsBetween(String value1, String value2) {
            addCriterion("thesis_keywords between", value1, value2, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisKeywordsNotBetween(String value1, String value2) {
            addCriterion("thesis_keywords not between", value1, value2, "thesisKeywords");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeIsNull() {
            addCriterion("thesis_school_code is null");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeIsNotNull() {
            addCriterion("thesis_school_code is not null");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeEqualTo(String value) {
            addCriterion("thesis_school_code =", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeNotEqualTo(String value) {
            addCriterion("thesis_school_code <>", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeGreaterThan(String value) {
            addCriterion("thesis_school_code >", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_school_code >=", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeLessThan(String value) {
            addCriterion("thesis_school_code <", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeLessThanOrEqualTo(String value) {
            addCriterion("thesis_school_code <=", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeLike(String value) {
            addCriterion("thesis_school_code like", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeNotLike(String value) {
            addCriterion("thesis_school_code not like", value, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeIn(List<String> values) {
            addCriterion("thesis_school_code in", values, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeNotIn(List<String> values) {
            addCriterion("thesis_school_code not in", values, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeBetween(String value1, String value2) {
            addCriterion("thesis_school_code between", value1, value2, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolCodeNotBetween(String value1, String value2) {
            addCriterion("thesis_school_code not between", value1, value2, "thesisSchoolCode");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameIsNull() {
            addCriterion("thesis_school_name is null");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameIsNotNull() {
            addCriterion("thesis_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameEqualTo(String value) {
            addCriterion("thesis_school_name =", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameNotEqualTo(String value) {
            addCriterion("thesis_school_name <>", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameGreaterThan(String value) {
            addCriterion("thesis_school_name >", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_school_name >=", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameLessThan(String value) {
            addCriterion("thesis_school_name <", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("thesis_school_name <=", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameLike(String value) {
            addCriterion("thesis_school_name like", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameNotLike(String value) {
            addCriterion("thesis_school_name not like", value, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameIn(List<String> values) {
            addCriterion("thesis_school_name in", values, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameNotIn(List<String> values) {
            addCriterion("thesis_school_name not in", values, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameBetween(String value1, String value2) {
            addCriterion("thesis_school_name between", value1, value2, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSchoolNameNotBetween(String value1, String value2) {
            addCriterion("thesis_school_name not between", value1, value2, "thesisSchoolName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeIsNull() {
            addCriterion("thesis_subject_code is null");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeIsNotNull() {
            addCriterion("thesis_subject_code is not null");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeEqualTo(String value) {
            addCriterion("thesis_subject_code =", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeNotEqualTo(String value) {
            addCriterion("thesis_subject_code <>", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeGreaterThan(String value) {
            addCriterion("thesis_subject_code >", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_subject_code >=", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeLessThan(String value) {
            addCriterion("thesis_subject_code <", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeLessThanOrEqualTo(String value) {
            addCriterion("thesis_subject_code <=", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeLike(String value) {
            addCriterion("thesis_subject_code like", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeNotLike(String value) {
            addCriterion("thesis_subject_code not like", value, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeIn(List<String> values) {
            addCriterion("thesis_subject_code in", values, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeNotIn(List<String> values) {
            addCriterion("thesis_subject_code not in", values, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeBetween(String value1, String value2) {
            addCriterion("thesis_subject_code between", value1, value2, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectCodeNotBetween(String value1, String value2) {
            addCriterion("thesis_subject_code not between", value1, value2, "thesisSubjectCode");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameIsNull() {
            addCriterion("thesis_subject_name is null");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameIsNotNull() {
            addCriterion("thesis_subject_name is not null");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameEqualTo(String value) {
            addCriterion("thesis_subject_name =", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameNotEqualTo(String value) {
            addCriterion("thesis_subject_name <>", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameGreaterThan(String value) {
            addCriterion("thesis_subject_name >", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_subject_name >=", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameLessThan(String value) {
            addCriterion("thesis_subject_name <", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("thesis_subject_name <=", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameLike(String value) {
            addCriterion("thesis_subject_name like", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameNotLike(String value) {
            addCriterion("thesis_subject_name not like", value, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameIn(List<String> values) {
            addCriterion("thesis_subject_name in", values, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameNotIn(List<String> values) {
            addCriterion("thesis_subject_name not in", values, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameBetween(String value1, String value2) {
            addCriterion("thesis_subject_name between", value1, value2, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisSubjectNameNotBetween(String value1, String value2) {
            addCriterion("thesis_subject_name not between", value1, value2, "thesisSubjectName");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeIsNull() {
            addCriterion("thesis_author_degree is null");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeIsNotNull() {
            addCriterion("thesis_author_degree is not null");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeEqualTo(String value) {
            addCriterion("thesis_author_degree =", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeNotEqualTo(String value) {
            addCriterion("thesis_author_degree <>", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeGreaterThan(String value) {
            addCriterion("thesis_author_degree >", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_author_degree >=", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeLessThan(String value) {
            addCriterion("thesis_author_degree <", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeLessThanOrEqualTo(String value) {
            addCriterion("thesis_author_degree <=", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeLike(String value) {
            addCriterion("thesis_author_degree like", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeNotLike(String value) {
            addCriterion("thesis_author_degree not like", value, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeIn(List<String> values) {
            addCriterion("thesis_author_degree in", values, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeNotIn(List<String> values) {
            addCriterion("thesis_author_degree not in", values, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeBetween(String value1, String value2) {
            addCriterion("thesis_author_degree between", value1, value2, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisAuthorDegreeNotBetween(String value1, String value2) {
            addCriterion("thesis_author_degree not between", value1, value2, "thesisAuthorDegree");
            return (Criteria) this;
        }

        public Criteria andThesisYearIsNull() {
            addCriterion("thesis_year is null");
            return (Criteria) this;
        }

        public Criteria andThesisYearIsNotNull() {
            addCriterion("thesis_year is not null");
            return (Criteria) this;
        }

        public Criteria andThesisYearEqualTo(Integer value) {
            addCriterion("thesis_year =", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearNotEqualTo(Integer value) {
            addCriterion("thesis_year <>", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearGreaterThan(Integer value) {
            addCriterion("thesis_year >", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("thesis_year >=", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearLessThan(Integer value) {
            addCriterion("thesis_year <", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearLessThanOrEqualTo(Integer value) {
            addCriterion("thesis_year <=", value, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearIn(List<Integer> values) {
            addCriterion("thesis_year in", values, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearNotIn(List<Integer> values) {
            addCriterion("thesis_year not in", values, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearBetween(Integer value1, Integer value2) {
            addCriterion("thesis_year between", value1, value2, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisYearNotBetween(Integer value1, Integer value2) {
            addCriterion("thesis_year not between", value1, value2, "thesisYear");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeIsNull() {
            addCriterion("thesis_committee is null");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeIsNotNull() {
            addCriterion("thesis_committee is not null");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeEqualTo(String value) {
            addCriterion("thesis_committee =", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeNotEqualTo(String value) {
            addCriterion("thesis_committee <>", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeGreaterThan(String value) {
            addCriterion("thesis_committee >", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_committee >=", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeLessThan(String value) {
            addCriterion("thesis_committee <", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeLessThanOrEqualTo(String value) {
            addCriterion("thesis_committee <=", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeLike(String value) {
            addCriterion("thesis_committee like", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeNotLike(String value) {
            addCriterion("thesis_committee not like", value, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeIn(List<String> values) {
            addCriterion("thesis_committee in", values, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeNotIn(List<String> values) {
            addCriterion("thesis_committee not in", values, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeBetween(String value1, String value2) {
            addCriterion("thesis_committee between", value1, value2, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisCommitteeNotBetween(String value1, String value2) {
            addCriterion("thesis_committee not between", value1, value2, "thesisCommittee");
            return (Criteria) this;
        }

        public Criteria andThesisLangIsNull() {
            addCriterion("thesis_lang is null");
            return (Criteria) this;
        }

        public Criteria andThesisLangIsNotNull() {
            addCriterion("thesis_lang is not null");
            return (Criteria) this;
        }

        public Criteria andThesisLangEqualTo(String value) {
            addCriterion("thesis_lang =", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangNotEqualTo(String value) {
            addCriterion("thesis_lang <>", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangGreaterThan(String value) {
            addCriterion("thesis_lang >", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_lang >=", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangLessThan(String value) {
            addCriterion("thesis_lang <", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangLessThanOrEqualTo(String value) {
            addCriterion("thesis_lang <=", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangLike(String value) {
            addCriterion("thesis_lang like", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangNotLike(String value) {
            addCriterion("thesis_lang not like", value, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangIn(List<String> values) {
            addCriterion("thesis_lang in", values, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangNotIn(List<String> values) {
            addCriterion("thesis_lang not in", values, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangBetween(String value1, String value2) {
            addCriterion("thesis_lang between", value1, value2, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisLangNotBetween(String value1, String value2) {
            addCriterion("thesis_lang not between", value1, value2, "thesisLang");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceIsNull() {
            addCriterion("thesis_publish_place is null");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceIsNotNull() {
            addCriterion("thesis_publish_place is not null");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceEqualTo(String value) {
            addCriterion("thesis_publish_place =", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceNotEqualTo(String value) {
            addCriterion("thesis_publish_place <>", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceGreaterThan(String value) {
            addCriterion("thesis_publish_place >", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_publish_place >=", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceLessThan(String value) {
            addCriterion("thesis_publish_place <", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceLessThanOrEqualTo(String value) {
            addCriterion("thesis_publish_place <=", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceLike(String value) {
            addCriterion("thesis_publish_place like", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceNotLike(String value) {
            addCriterion("thesis_publish_place not like", value, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceIn(List<String> values) {
            addCriterion("thesis_publish_place in", values, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceNotIn(List<String> values) {
            addCriterion("thesis_publish_place not in", values, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceBetween(String value1, String value2) {
            addCriterion("thesis_publish_place between", value1, value2, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisPublishPlaceNotBetween(String value1, String value2) {
            addCriterion("thesis_publish_place not between", value1, value2, "thesisPublishPlace");
            return (Criteria) this;
        }

        public Criteria andThesisCountryIsNull() {
            addCriterion("thesis_country is null");
            return (Criteria) this;
        }

        public Criteria andThesisCountryIsNotNull() {
            addCriterion("thesis_country is not null");
            return (Criteria) this;
        }

        public Criteria andThesisCountryEqualTo(String value) {
            addCriterion("thesis_country =", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryNotEqualTo(String value) {
            addCriterion("thesis_country <>", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryGreaterThan(String value) {
            addCriterion("thesis_country >", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_country >=", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryLessThan(String value) {
            addCriterion("thesis_country <", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryLessThanOrEqualTo(String value) {
            addCriterion("thesis_country <=", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryLike(String value) {
            addCriterion("thesis_country like", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryNotLike(String value) {
            addCriterion("thesis_country not like", value, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryIn(List<String> values) {
            addCriterion("thesis_country in", values, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryNotIn(List<String> values) {
            addCriterion("thesis_country not in", values, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryBetween(String value1, String value2) {
            addCriterion("thesis_country between", value1, value2, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisCountryNotBetween(String value1, String value2) {
            addCriterion("thesis_country not between", value1, value2, "thesisCountry");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeIsNull() {
            addCriterion("thesis_degree is null");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeIsNotNull() {
            addCriterion("thesis_degree is not null");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeEqualTo(String value) {
            addCriterion("thesis_degree =", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeNotEqualTo(String value) {
            addCriterion("thesis_degree <>", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeGreaterThan(String value) {
            addCriterion("thesis_degree >", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_degree >=", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeLessThan(String value) {
            addCriterion("thesis_degree <", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeLessThanOrEqualTo(String value) {
            addCriterion("thesis_degree <=", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeLike(String value) {
            addCriterion("thesis_degree like", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeNotLike(String value) {
            addCriterion("thesis_degree not like", value, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeIn(List<String> values) {
            addCriterion("thesis_degree in", values, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeNotIn(List<String> values) {
            addCriterion("thesis_degree not in", values, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeBetween(String value1, String value2) {
            addCriterion("thesis_degree between", value1, value2, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisDegreeNotBetween(String value1, String value2) {
            addCriterion("thesis_degree not between", value1, value2, "thesisDegree");
            return (Criteria) this;
        }

        public Criteria andThesisTypeIsNull() {
            addCriterion("thesis_type is null");
            return (Criteria) this;
        }

        public Criteria andThesisTypeIsNotNull() {
            addCriterion("thesis_type is not null");
            return (Criteria) this;
        }

        public Criteria andThesisTypeEqualTo(String value) {
            addCriterion("thesis_type =", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeNotEqualTo(String value) {
            addCriterion("thesis_type <>", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeGreaterThan(String value) {
            addCriterion("thesis_type >", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_type >=", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeLessThan(String value) {
            addCriterion("thesis_type <", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeLessThanOrEqualTo(String value) {
            addCriterion("thesis_type <=", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeLike(String value) {
            addCriterion("thesis_type like", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeNotLike(String value) {
            addCriterion("thesis_type not like", value, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeIn(List<String> values) {
            addCriterion("thesis_type in", values, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeNotIn(List<String> values) {
            addCriterion("thesis_type not in", values, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeBetween(String value1, String value2) {
            addCriterion("thesis_type between", value1, value2, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisTypeNotBetween(String value1, String value2) {
            addCriterion("thesis_type not between", value1, value2, "thesisType");
            return (Criteria) this;
        }

        public Criteria andThesisUrlIsNull() {
            addCriterion("thesis_url is null");
            return (Criteria) this;
        }

        public Criteria andThesisUrlIsNotNull() {
            addCriterion("thesis_url is not null");
            return (Criteria) this;
        }

        public Criteria andThesisUrlEqualTo(String value) {
            addCriterion("thesis_url =", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlNotEqualTo(String value) {
            addCriterion("thesis_url <>", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlGreaterThan(String value) {
            addCriterion("thesis_url >", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_url >=", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlLessThan(String value) {
            addCriterion("thesis_url <", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlLessThanOrEqualTo(String value) {
            addCriterion("thesis_url <=", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlLike(String value) {
            addCriterion("thesis_url like", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlNotLike(String value) {
            addCriterion("thesis_url not like", value, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlIn(List<String> values) {
            addCriterion("thesis_url in", values, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlNotIn(List<String> values) {
            addCriterion("thesis_url not in", values, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlBetween(String value1, String value2) {
            addCriterion("thesis_url between", value1, value2, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisUrlNotBetween(String value1, String value2) {
            addCriterion("thesis_url not between", value1, value2, "thesisUrl");
            return (Criteria) this;
        }

        public Criteria andThesisStatusIsNull() {
            addCriterion("thesis_status is null");
            return (Criteria) this;
        }

        public Criteria andThesisStatusIsNotNull() {
            addCriterion("thesis_status is not null");
            return (Criteria) this;
        }

        public Criteria andThesisStatusEqualTo(String value) {
            addCriterion("thesis_status =", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusNotEqualTo(String value) {
            addCriterion("thesis_status <>", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusGreaterThan(String value) {
            addCriterion("thesis_status >", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_status >=", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusLessThan(String value) {
            addCriterion("thesis_status <", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusLessThanOrEqualTo(String value) {
            addCriterion("thesis_status <=", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusLike(String value) {
            addCriterion("thesis_status like", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusNotLike(String value) {
            addCriterion("thesis_status not like", value, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusIn(List<String> values) {
            addCriterion("thesis_status in", values, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusNotIn(List<String> values) {
            addCriterion("thesis_status not in", values, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusBetween(String value1, String value2) {
            addCriterion("thesis_status between", value1, value2, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisStatusNotBetween(String value1, String value2) {
            addCriterion("thesis_status not between", value1, value2, "thesisStatus");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextIsNull() {
            addCriterion("thesis_fulltext is null");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextIsNotNull() {
            addCriterion("thesis_fulltext is not null");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextEqualTo(String value) {
            addCriterion("thesis_fulltext =", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextNotEqualTo(String value) {
            addCriterion("thesis_fulltext <>", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextGreaterThan(String value) {
            addCriterion("thesis_fulltext >", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextGreaterThanOrEqualTo(String value) {
            addCriterion("thesis_fulltext >=", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextLessThan(String value) {
            addCriterion("thesis_fulltext <", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextLessThanOrEqualTo(String value) {
            addCriterion("thesis_fulltext <=", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextLike(String value) {
            addCriterion("thesis_fulltext like", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextNotLike(String value) {
            addCriterion("thesis_fulltext not like", value, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextIn(List<String> values) {
            addCriterion("thesis_fulltext in", values, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextNotIn(List<String> values) {
            addCriterion("thesis_fulltext not in", values, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextBetween(String value1, String value2) {
            addCriterion("thesis_fulltext between", value1, value2, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andThesisFulltextNotBetween(String value1, String value2) {
            addCriterion("thesis_fulltext not between", value1, value2, "thesisFulltext");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIsNull() {
            addCriterion("order_batch is null");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIsNotNull() {
            addCriterion("order_batch is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBatchEqualTo(Long value) {
            addCriterion("order_batch =", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchNotEqualTo(Long value) {
            addCriterion("order_batch <>", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchGreaterThan(Long value) {
            addCriterion("order_batch >", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchGreaterThanOrEqualTo(Long value) {
            addCriterion("order_batch >=", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchLessThan(Long value) {
            addCriterion("order_batch <", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchLessThanOrEqualTo(Long value) {
            addCriterion("order_batch <=", value, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchIn(List<Long> values) {
            addCriterion("order_batch in", values, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchNotIn(List<Long> values) {
            addCriterion("order_batch not in", values, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchBetween(Long value1, Long value2) {
            addCriterion("order_batch between", value1, value2, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andOrderBatchNotBetween(Long value1, Long value2) {
            addCriterion("order_batch not between", value1, value2, "orderBatch");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearIsNull() {
            addCriterion("purchase_year is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearIsNotNull() {
            addCriterion("purchase_year is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearEqualTo(Integer value) {
            addCriterion("purchase_year =", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearNotEqualTo(Integer value) {
            addCriterion("purchase_year <>", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearGreaterThan(Integer value) {
            addCriterion("purchase_year >", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("purchase_year >=", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearLessThan(Integer value) {
            addCriterion("purchase_year <", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearLessThanOrEqualTo(Integer value) {
            addCriterion("purchase_year <=", value, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearIn(List<Integer> values) {
            addCriterion("purchase_year in", values, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearNotIn(List<Integer> values) {
            addCriterion("purchase_year not in", values, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearBetween(Integer value1, Integer value2) {
            addCriterion("purchase_year between", value1, value2, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseYearNotBetween(Integer value1, Integer value2) {
            addCriterion("purchase_year not between", value1, value2, "purchaseYear");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgIsNull() {
            addCriterion("purchase_org is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgIsNotNull() {
            addCriterion("purchase_org is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgEqualTo(Long value) {
            addCriterion("purchase_org =", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgNotEqualTo(Long value) {
            addCriterion("purchase_org <>", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgGreaterThan(Long value) {
            addCriterion("purchase_org >", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgGreaterThanOrEqualTo(Long value) {
            addCriterion("purchase_org >=", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgLessThan(Long value) {
            addCriterion("purchase_org <", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgLessThanOrEqualTo(Long value) {
            addCriterion("purchase_org <=", value, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgIn(List<Long> values) {
            addCriterion("purchase_org in", values, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgNotIn(List<Long> values) {
            addCriterion("purchase_org not in", values, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgBetween(Long value1, Long value2) {
            addCriterion("purchase_org between", value1, value2, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseOrgNotBetween(Long value1, Long value2) {
            addCriterion("purchase_org not between", value1, value2, "purchaseOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupIsNull() {
            addCriterion("purchase_group is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupIsNotNull() {
            addCriterion("purchase_group is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupEqualTo(Long value) {
            addCriterion("purchase_group =", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupNotEqualTo(Long value) {
            addCriterion("purchase_group <>", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupGreaterThan(Long value) {
            addCriterion("purchase_group >", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupGreaterThanOrEqualTo(Long value) {
            addCriterion("purchase_group >=", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupLessThan(Long value) {
            addCriterion("purchase_group <", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupLessThanOrEqualTo(Long value) {
            addCriterion("purchase_group <=", value, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupIn(List<Long> values) {
            addCriterion("purchase_group in", values, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupNotIn(List<Long> values) {
            addCriterion("purchase_group not in", values, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupBetween(Long value1, Long value2) {
            addCriterion("purchase_group between", value1, value2, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andPurchaseGroupNotBetween(Long value1, Long value2) {
            addCriterion("purchase_group not between", value1, value2, "purchaseGroup");
            return (Criteria) this;
        }

        public Criteria andMarcBatchIsNull() {
            addCriterion("marc_batch is null");
            return (Criteria) this;
        }

        public Criteria andMarcBatchIsNotNull() {
            addCriterion("marc_batch is not null");
            return (Criteria) this;
        }

        public Criteria andMarcBatchEqualTo(Long value) {
            addCriterion("marc_batch =", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchNotEqualTo(Long value) {
            addCriterion("marc_batch <>", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchGreaterThan(Long value) {
            addCriterion("marc_batch >", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchGreaterThanOrEqualTo(Long value) {
            addCriterion("marc_batch >=", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchLessThan(Long value) {
            addCriterion("marc_batch <", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchLessThanOrEqualTo(Long value) {
            addCriterion("marc_batch <=", value, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchIn(List<Long> values) {
            addCriterion("marc_batch in", values, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchNotIn(List<Long> values) {
            addCriterion("marc_batch not in", values, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchBetween(Long value1, Long value2) {
            addCriterion("marc_batch between", value1, value2, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andMarcBatchNotBetween(Long value1, Long value2) {
            addCriterion("marc_batch not between", value1, value2, "marcBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchIsNull() {
            addCriterion("pdf_batch is null");
            return (Criteria) this;
        }

        public Criteria andPdfBatchIsNotNull() {
            addCriterion("pdf_batch is not null");
            return (Criteria) this;
        }

        public Criteria andPdfBatchEqualTo(Long value) {
            addCriterion("pdf_batch =", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchNotEqualTo(Long value) {
            addCriterion("pdf_batch <>", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchGreaterThan(Long value) {
            addCriterion("pdf_batch >", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchGreaterThanOrEqualTo(Long value) {
            addCriterion("pdf_batch >=", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchLessThan(Long value) {
            addCriterion("pdf_batch <", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchLessThanOrEqualTo(Long value) {
            addCriterion("pdf_batch <=", value, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchIn(List<Long> values) {
            addCriterion("pdf_batch in", values, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchNotIn(List<Long> values) {
            addCriterion("pdf_batch not in", values, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchBetween(Long value1, Long value2) {
            addCriterion("pdf_batch between", value1, value2, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfBatchNotBetween(Long value1, Long value2) {
            addCriterion("pdf_batch not between", value1, value2, "pdfBatch");
            return (Criteria) this;
        }

        public Criteria andPdfPagesIsNull() {
            addCriterion("pdf_pages is null");
            return (Criteria) this;
        }

        public Criteria andPdfPagesIsNotNull() {
            addCriterion("pdf_pages is not null");
            return (Criteria) this;
        }

        public Criteria andPdfPagesEqualTo(Integer value) {
            addCriterion("pdf_pages =", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesNotEqualTo(Integer value) {
            addCriterion("pdf_pages <>", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesGreaterThan(Integer value) {
            addCriterion("pdf_pages >", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesGreaterThanOrEqualTo(Integer value) {
            addCriterion("pdf_pages >=", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesLessThan(Integer value) {
            addCriterion("pdf_pages <", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesLessThanOrEqualTo(Integer value) {
            addCriterion("pdf_pages <=", value, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesIn(List<Integer> values) {
            addCriterion("pdf_pages in", values, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesNotIn(List<Integer> values) {
            addCriterion("pdf_pages not in", values, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesBetween(Integer value1, Integer value2) {
            addCriterion("pdf_pages between", value1, value2, "pdfPages");
            return (Criteria) this;
        }

        public Criteria andPdfPagesNotBetween(Integer value1, Integer value2) {
            addCriterion("pdf_pages not between", value1, value2, "pdfPages");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_thesis
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}